### ISSUE TITLE
Google Forms

### ISSUE THREAD

**Issue by davidesteve** [junaid33/opensource.builders#471]
[LIberaForms](http://www.liberaforms.org) is an ethical and privacy focused alternative to Google Forms.
Repo [https://gitlab.com/liberaforms](https://gitlab.com/liberaforms)

**Comment by jcklpe** [comment]
@davidesteve  wrong format. Closed source goes in title, the open source options go in the body or comments of the ticket. Setting this to "invalid" if not fixed within 30 days I'll close as invalid. Thank you.

**Comment by davidesteve** [comment]
Fixed main post, as far as I understood.

**Comment by jcklpe** [comment]
@davidesteve  still not the right format. LiberaForms is the open source right? So the open source goes in the comments, and the title should be the closed source software that it is an alternative to. Literally just look at any other issue ticket in this repo to see what the pattern is.   
 

![](https://user-images.githubusercontent.com/9451726/206583805-67fceb8b-0bd8-430e-834a-5640d1cd3ce4.png)

**Comment by davidesteve** [comment]
I did not get it, sorry. Now I think I did, thanks for your patience :)

**Comment by jcklpe** [comment]
No worries! Thank you for the contribution!
